version: '3.5'

services:
  docker-dashboard-api:
    image: ${REGISTRY}docker-dashboard-api:${TAG:-latest}
    secrets:
      - dockerregistrysecrets
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    ports:
      - "6099:80"
    build:
      context: .
      dockerfile: DockerDashboard.Api/Dockerfile
    env_file:
      - ../dashboard.env

secrets:
  dockerregistrysecrets:
    file: ../secrets/docker_registry_pwd.txt
