version: '3.5'

services:
  docker-dashboard-api:
    image: docker-dashboard-api:latest
    secrets:
      - dockerregistrysecrets
    environment:
      Settings_SwarmUrl: ${SWARM_URL}
    ports:
      - "6099:80"
    build:
      context: .
      dockerfile: DockerDashboard.Api/Dockerfile

secrets:
  dockerregistrysecrets:
    file: ../secrets/docker_registry_pwd.txt
